// <auto-generated />
using System;
using LMSProjectApi.DBConnect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LMSProjectApi.Migrations
{
    [DbContext(typeof(LMS_DataContext))]
    [Migration("20220907180949_initlms")]
    partial class initlms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LMSProjectApi.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Emp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Avail_Leave_Bal")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Emp_Doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emp_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Emp_Mobileno")
                        .HasColumnType("int");

                    b.Property<string>("Emp_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Repassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LMSProjectApi.Models.LeaveModel", b =>
                {
                    b.Property<int>("Leave_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Applied_On")
                        .HasColumnType("datetime2");

                    b.Property<int>("Emp_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leave_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manager_id")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Leave_Id");

                    b.HasIndex("Emp_id");

                    b.HasIndex("Manager_id");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("LMSProjectApi.Models.ManagerModel", b =>
                {
                    b.Property<int>("Manager_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeEmp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Manager_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manager_Mobileno")
                        .HasColumnType("int");

                    b.Property<string>("Manager_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Repassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Manager_Id");

                    b.HasIndex("EmployeeEmp_Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("LMSProjectApi.Models.LeaveModel", b =>
                {
                    b.HasOne("LMSProjectApi.Models.EmployeeModel", "EmployeeModel")
                        .WithMany()
                        .HasForeignKey("Emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMSProjectApi.Models.ManagerModel", "ManagerModel")
                        .WithMany()
                        .HasForeignKey("Manager_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeModel");

                    b.Navigation("ManagerModel");
                });

            modelBuilder.Entity("LMSProjectApi.Models.ManagerModel", b =>
                {
                    b.HasOne("LMSProjectApi.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeEmp_Id");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
